version: '3'
services:
  web:
    build: .
    ports:
      - "8088:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

